- name: test
  debug:
    msg: "{{ ansible_env.XDG_DATA_HOME }}"

- name: is installed plug
  become_user: vagrant
  shell: test -f "{{ ansible_env.XDG_DATA_HOME }}/nvim/site/autoload/plug.vim"
  register: plug_installed
  failed_when: plug_installed.rc not in [0, 1]

- name: create plug dirs
  become_user: vagrant
  file:
    path: "{{ ansible_env.XDG_DATA_HOME }}/nvim/site/autoload"
    owner: vagrant
    group: vagrant
    state: directory
  when: plug_installed.rc == 1

- name: download plug
  become_user: vagrant
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.XDG_DATA_HOME }}/nvim/site/autoload/plug.vim"
    mode: "0644"
  when: plug_installed.rc == 1
