- name: add key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main'
    filename: google-cloud-sdk

- name: install deps
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    update_cache: yes

