- name: apt update
  apt:
    update_cache: 'yes'
    upgrade: 'yes'

- name: add apt repos
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - 'ppa:fish-shell/release-3'
    - 'ppa:git-core/ppa'
    - 'ppa:neovim-ppa/stable'

- name: install packages
  apt:
    pkg:
      - fish
      - git
      - neovim
      - python-neovim
      - python3-neovim
      - build-essential
      - curl
      - file
      - build-essential
    update_cache: yes

- name: upgrade all
  apt:
    upgrade: 'yes'
