- name: check golang plugin
  become_user: vagrant
  shell: asdf plugin list | grep -q golang
  register: golang_installed
  failed_when: golang_installed.rc not in [0, 1]

- name: add plugin
  become_user: vagrant
  shell: asdf plugin add golang
  when: golang_installed.rc == 1

- name: install golang
  become_user: vagrant
  shell: asdf install golang "{{ item }}"
  with_items:
    - 1.14

- name: set global golang
  become_user: vagrant
  shell: asdf global golang 1.14
