- name: check python plugin
  become_user: vagrant
  shell: asdf plugin list | grep -q python
  register: python_installed
  failed_when: python_installed.rc not in [0, 1]

- name: add plugin
  become_user: vagrant
  shell: asdf plugin add python
  when: python_installed.rc == 1

- name: install python
  become_user: vagrant
  shell: asdf install python "{{ item }}"
  with_items:
    - 3.8.2
    - 2.7.17

- name: set python  golang
  become_user: vagrant
  shell: asdf global python 3.8.2
